<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SokobanCLI.GameLogic</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SokobanCLI.Graphics\SokobanCLI.Graphics.csproj" />
    <ProjectReference Include="..\SokobanCLI.Models\SokobanCLI.Models.csproj" />
  </ItemGroup>

</Project>
